# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.5
  - nightly
notifications:
  email: true
jobs:
    include:
        script:
            - julia --project -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/dingraha/DanielIngrahamRegistry.git"))'
            - julia --project --check-bounds=yes -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test()'
