name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - '1' # Leave this line unchanged. '1' will automatically expand to the latest stable 1.x release of Julia.
          - 'nightly'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - name: Add General and DanielIngrahamRegistry
        shell: julia --color=yes {0}
        run: |
          using Pkg
          Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General"))
          # Pkg.Registry.add(RegistrySpec(url="https://github.com/dingraha/DanielIngrahamRegistry"))
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
      - uses: julia-actions/julia-runtest@v1
        env:
              JULIA_PKG_USE_CLI_GIT: 'true'
